spring.application.name=multimed
spring.datasource.url=jdbc:postgresql://localhost:5432/multimed2
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
